### ISSUE TITLE
Edit/Delete user - UI command

### ISSUE THREAD

**Issue by Hunroll** [Hunroll/-projetc-team-05#12]
How to select a proper user if we have 2 mathes???

**Comment by etosomsemnefiltry** [comment]
Проблемы с нахождением двух контактов не будет. 
Ответ на "почему":
"add Vasya 0631110011" - добавить Vasya в книгу.
"add Vasya 0990001100" - добавит номер телефона в контакт Vasya, если он есть. 

Таким образом, у нас не будет просто одинаковых имен в книге
