### ISSUE TITLE
Add help message

### ISSUE THREAD

**Issue by Guru01100101** [Hunroll/-projetc-team-05#23]
Add help message on help command or if wrong command.
Help message must contains explanation of program, list of commands with write format of arguments

**Comment by Guru01100101** [comment]
If error in command i see help message. Must be same when i type wrong command or "help"

**Comment by etosomsemnefiltry** [comment]
Сделал красивый табличный вывод команд в приветствии с цветом.

**Comment by Hunroll** [comment]
To be extended when notes/tags are added
